services:
  - type: web
    name: mony-api
    runtime: docker
    plan: free
    dockerfile: ./apps/api/Dockerfile
    envVars:
      - key: DATABASE_URL
        scope: service
        value: ${DATABASE_URL}
      - key: JWT_SECRET
        scope: service
        value: ${JWT_SECRET}
      - key: ENVIRONMENT
        value: production
